In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
df = pd.read_csv('Melbourne_housing_FULL.csv')

In [56]:
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0

In [57]:
df.nunique()

Suburb             351
Address          34009
Rooms               12
Type                 3
Price             2871
Method               9
SellerG            388
Date                78
Distance           215
Postcode           211
Bedroom2            15
Bathroom            11
Car                 15
Landsize          1684
BuildingArea       740
YearBuilt          160
CouncilArea         33
Lattitude        13402
Longtitude       14524
Regionname           8
Propertycount      342
dtype: int64

In [58]:
df.shape

(34857, 21)

In [59]:
cols_to_use = ['Suburb', 'Rooms', 'Type','Method', 'SellerG', 'Regionname', 'Propertycount','Distance', 'CouncilArea', 'Bedroom2', 'Bathroom', 'Car', 'Landsize', 'BuildingArea', 'Price']
df = df[cols_to_use]
df.head()

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2,h,SS,Jellis,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,126.0,NaN,NaN
1,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.0,NaN,1480000.0
2,Abbotsford,2,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,0.0,156.0,79.0,1035000.0
3,Abbotsford,3,u,VB,Rounds,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,1.0,0.0,NaN,NaN
4,Abbotsford,3,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,0.0,134.0,150.0,1465000.0

In [60]:
df.shape

(34857, 15)

In [61]:
df.isna().sum()

Suburb               0
Rooms                0
Type                 0
Method               0
SellerG              0
Regionname           3
Propertycount        3
Distance             1
CouncilArea          3
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
Price             7610
dtype: int64

In [62]:
cols_to_fill_zero = ['Propertycount','Distance','Bedroom2','Bathroom', 'Car']
df[cols_to_fill_zero] = df[cols_to_fill_zero].fillna(0)

In [63]:
df.isna().sum()

Suburb               0
Rooms                0
Type                 0
Method               0
SellerG              0
Regionname           3
Propertycount        0
Distance             0
CouncilArea          3
Bedroom2             0
Bathroom             0
Car                  0
Landsize         11810
BuildingArea     21115
Price             7610
dtype: int64

In [64]:
df['Landsize']= df['Landsize'].fillna(df['Landsize'].mean())
df['BuildingArea']= df['BuildingArea'].fillna(df['BuildingArea'].mean())

In [65]:
df.isna().sum()

Suburb              0
Rooms               0
Type                0
Method              0
SellerG             0
Regionname          3
Propertycount       0
Distance            0
CouncilArea         3
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
Price            7610
dtype: int64

In [66]:
df.dropna(inplace = True)
df.isna().sum()

Suburb           0
Rooms            0
Type             0
Method           0
SellerG          0
Regionname       0
Propertycount    0
Distance         0
CouncilArea      0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
Price            0
dtype: int64

In [67]:
df = pd.get_dummies(df,drop_first = True)

In [68]:
print(df.head())

   Rooms  Propertycount  Distance  Bedroom2  Bathroom  Car  Landsize  \
1      2         4019.0       2.5       2.0       1.0  1.0     202.0
2      2         4019.0       2.5       2.0       1.0  0.0     156.0
4      3         4019.0       2.5       3.0       2.0  0.0     134.0
5      3         4019.0       2.5       3.0       2.0  1.0      94.0
6      4         4019.0       2.5       3.0       1.0  2.0     120.0

   BuildingArea      Price  Suburb_Aberfeldie  ...  \
1      160.2564  1480000.0              False  ...
2       79.0000  1035000.0              False  ...
4      150.0000  1465000.0              False  ...
5      160.2564   850000.0              False  ...
6      142.0000  1600000.0              False  ...

   CouncilArea_Moorabool Shire Council  CouncilArea_Moreland City Council  \
1                                False                              False
2                                False                              False
4                                False                              False
5                                False                              False
6                                False                              False

   CouncilArea_Nillumbik Shire Council  CouncilArea_Port Phillip City Council  \
1                                False                                  False
2                                False                                  False
4                                False                                  False
5                                False                                  False
6                                False                                  False

   CouncilArea_Stonnington City Council  CouncilArea_Whitehorse City Council  \
1                                 False                                False
2                                 False                                False
4                                 False                                False
5                                 False                                False
6                                 False                                False

   CouncilArea_Whittlesea City Council  CouncilArea_Wyndham City Council  \
1                                False                             False
2                                False                             False
4                                False                             False
5                                False                             False
6                                False                             False

   CouncilArea_Yarra City Council  CouncilArea_Yarra Ranges Shire Council
1                            True                                   False
2                            True                                   False
4                            True                                   False
5                            True                                   False
6                            True                                   False

[5 rows x 745 columns]

In [69]:
X = df.drop('Price', axis = 1)
y = df['Price']

In [70]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 2)

In [73]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.1385368316158062

example of overfitting

In [74]:
lr.score(X_train, y_train)

0.6827792395792722

L1/ lasso

In [78]:
from sklearn import linear_model
lasso = linear_model.Lasso(alpha = 50,max_iter=1000,tol=0.1)
lasso.fit(X_train, y_train)

Lasso(alpha=50, tol=0.1)

In [79]:
lasso.score(X_test, y_test)

0.6636280170612754

In [80]:
lasso.score(X_train, y_train)

0.6767149418617551

In [84]:
from sklearn.linear_model import Ridge
ridge = linear_model.Ridge(alpha = 50,max_iter=1000,tol=0.1)
ridge.fit(X_train, y_train)
ridge.score(X_test, y_test)

0.6670848945194974

In [85]:
ridge.score(X_train, y_train)

0.6622376739684326