In [27]:
import pandas as pd

In [28]:
df = pd.read_excel("survey.xls")
df

      Name Nationality     Sex  Age Handedness
0    Kathy         USA  Female   23      Right
1    Linda         USA  Female   18      Right
2    Peter         USA    Male   19      Right
3     John         USA    Male   22       Left
4   Fatima   Bangadesh  Female   31       Left
5    Kadir   Bangadesh    Male   25       Left
6   Dhaval       India    Male   35       Left
7   Sudhir       India    Male   31       Left
8   Parvir       India    Male   37      Right
9      Yan       China  Female   52      Right
10    Juan       China  Female   58       Left
11   Liang       China    Male   43       Left

cross tab is under pandas not dataframe

In [29]:
pd.crosstab(df.Nationality,df.Handedness)

Handedness   Left  Right
Nationality
Bangadesh       2      0
China           2      1
India           2      1
USA             1      3

In [30]:
pd.crosstab(df.Sex,df.Handedness,margins=True) #3rd arg is margin

Handedness  Left  Right  All
Sex
Female         2      3    5
Male           5      2    7
All            7      5   12

In [31]:
pd.crosstab([df.Nationality,df.Sex],df.Handedness,margins=True)

Handedness          Left  Right  All
Nationality Sex
Bangadesh   Female     1      0    1
            Male       1      0    1
China       Female     1      1    2
            Male       1      0    1
India       Male       2      1    3
USA         Female     0      2    2
            Male       1      1    2
All                    7      5   12

In [32]:
pd.crosstab(df.Nationality,df.Handedness,normalize='index') #gives pct distribution

Handedness       Left     Right
Nationality
Bangadesh    1.000000  0.000000
China        0.666667  0.333333
India        0.666667  0.333333
USA          0.250000  0.750000

In [34]:
import numpy as np
pd.crosstab(df.Sex,df.Nationality,values=df.Age,aggfunc=np.average)

Nationality  Bangadesh  China      India   USA
Sex
Female            31.0   55.0        NaN  20.5
Male              25.0   43.0  34.333333  20.5